import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
const browser = await chromium.launch({channel:'msedge',headless:true})
const page = await browser.newPage({viewport:{width:1600,height:900}})
const previewUrl=process.env.PREVIEW_URL||'http://127.0.0.1:5174/prototypes/purchase-progress.html'
const standalone=previewUrl.startsWith('file:')
if(standalone) await page.context().setOffline(true)
page.setDefaultTimeout(10000)
const errors=[], api=[]
page.on('pageerror',e=>errors.push(e.message))
page.on('request',r=>{const u=new URL(r.url());if(u.pathname.startsWith('/api/')||(standalone&&['http:','https:'].includes(u.protocol)))api.push(r.url())})
try {
  await page.goto(previewUrl)
  await page.evaluate(()=>document.fonts.ready)
  await expect(page.getByRole('button',{name:'明细',exact:true})).toHaveCount(12)
  await page.screenshot({path:'../.runtime/purchase-report-1600.png'})
  await page.getByRole('button',{name:'明细',exact:true}).first().click()
  const drawer=page.getByRole('dialog',{name:'采购关联明细'})
  await expect(drawer.locator('.orders-table tbody tr')).toHaveCount(3)
  await expect(drawer.locator('.receipts-table tbody tr')).toHaveCount(3)
  await expect(drawer.locator('.receipts-table tfoot')).toContainText('45')
  await expect(drawer.locator('.quantity-strip,.order-block')).toHaveCount(0)
  await drawer.getByRole('button',{name:'CGDD0005821',exact:true}).click()
  await expect(drawer.locator('.receipts-table tbody tr')).toHaveCount(2)
  await expect(drawer.locator('.receipts-table tfoot')).toContainText('35')
  await drawer.getByRole('button',{name:'CGDD0005872',exact:true}).click()
  await expect(drawer.getByText('此订单暂无入库记录')).toBeVisible()
  await drawer.getByRole('button',{name:'查看全部',exact:true}).click()
  await expect(drawer.locator('.receipts-table tbody tr')).toHaveCount(3)
  await page.screenshot({path:'../.runtime/purchase-report-detail-1600.png'})
  await page.getByRole('button',{name:'关闭采购明细'}).click()
  await page.getByRole('textbox',{name:'搜索采购明细'}).fill('加热器')
  await page.getByRole('button',{name:'明细',exact:true}).click()
  await expect(drawer.locator('.orders-table tbody tr')).toHaveCount(2)
  await expect(drawer.locator('.receipts-table tbody tr')).toHaveCount(2)
  await expect(drawer.locator('.orders-table tfoot')).toContainText('12')
  await expect(drawer.locator('.receipts-table tfoot')).toContainText('6')
  await expect(drawer.getByRole('button',{name:'查看全部',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'关闭采购明细'}).click()
  await page.getByRole('button',{name:'重置',exact:true}).click()
  await page.getByRole('button',{name:'未下单',exact:true}).click()
  await expect(page.getByRole('button',{name:'明细',exact:true})).toHaveCount(2)
  await page.getByRole('button',{name:'明细',exact:true}).first().click()
  await expect(drawer.getByText('尚未形成采购订单')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'重置',exact:true}).click()
  await page.getByRole('textbox',{name:'搜索采购明细'}).fill('气动隔膜')
  await expect(page.getByRole('button',{name:'明细',exact:true})).toHaveCount(1)
  await page.getByRole('button',{name:'保存查询方案',exact:true}).click()
  await page.getByRole('textbox',{name:'方案名称'}).fill('隔膜阀跟踪')
  await page.getByRole('button',{name:'保存',exact:true}).click()
  await page.reload()
  await page.getByRole('button',{name:/当前查询/}).click()
  await page.getByText('隔膜阀跟踪',{exact:true}).click()
  await expect(page.getByRole('textbox',{name:'搜索采购明细'})).toHaveValue('气动隔膜')
  await page.getByRole('button',{name:'列设置',exact:true}).click()
  await page.locator('.el-checkbox').filter({hasText:'规格型号'}).click()
  await expect(page.getByRole('checkbox',{name:'规格型号',exact:true})).toBeChecked()
  await page.getByRole('button',{name:'完成',exact:true}).click()
  await page.getByRole('button',{name:'重置',exact:true}).click()
  for(const viewport of [{width:1366,height:768},{width:390,height:844}]){
    await page.setViewportSize(viewport)
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    await page.screenshot({path:`../.runtime/purchase-report-${viewport.width}.png`})
    await page.getByRole('button',{name:'明细',exact:true}).first().click()
    const box=await drawer.boundingBox()
    assert.ok(box.x>=0 && box.x+box.width<=viewport.width)
    await page.screenshot({path:`../.runtime/purchase-report-detail-${viewport.width}.png`})
    await page.getByRole('button',{name:'关闭采购明细'}).click()
  }
  assert.deepEqual(errors,[])
  assert.deepEqual(api,[])
  console.log('PASS: list, split orders, receipts, empty state, filtering, persisted plan, columns, responsive; no business API requests')
} finally {if(errors.length)console.error(errors);await browser.close()}
