import { chromium, expect } from '@playwright/test'

const browser = await chromium.launch({ channel: 'msedge' })
try {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } })
  const errors = [], requests = []
  page.on('pageerror', e => errors.push(e.message))
  await page.route('**/api/**', route => { requests.push(route.request().url()); return route.abort() })
  await page.goto('http://127.0.0.1:5191/prototypes/report-query.html')
  const query = page.getByRole('button', { name: '查询', exact: true })
  await expect(page.getByText('尚未查询', { exact: true })).toBeVisible()
  await query.click()
  await expect(page.locator('.rq-pagination')).toContainText('共 68 条')
  await page.getByRole('textbox', { name: '物料', exact: true }).fill('PFA')
  await expect(page.getByText('条件已修改，待查询')).toBeVisible()
  await expect(page.locator('.rq-pagination')).toContainText('共 68 条')
  await page.getByRole('button', { name: '导出', exact: true }).click()
  await expect(page.getByText('当前修改的条件尚未查询，不包含在本次导出中。')).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: '取消' }).click()
  await page.getByRole('button', { name: '更多条件' }).click()
  await page.getByRole('button', { name: '添加条件' }).click()
  await page.getByRole('textbox', { name: '条件1值', exact: true }).fill('180')
  await page.waitForTimeout(350)
  await page.screenshot({ path: '/tmp/pms-query-conditions.png' })
  await page.getByRole('button', { name: '应用条件' }).click()
  await expect(page.locator('.rq-tags')).toContainText('180')
  await expect(page.locator('.rq-pagination')).toContainText('共 68 条')
  await page.getByRole('button', { name: '保存方案' }).click()
  await page.getByRole('textbox', { name: '方案名称' }).fill('研发物料')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('查询方案已保存到此样稿')).toBeVisible()
  await page.getByRole('button', { name: '物料收发明细', exact: true }).click()
  await expect(query).toBeDisabled()
  await page.getByRole('textbox', { name: '物料', exact: true }).fill('180102020045')
  await expect(query).toBeDisabled()
  await page.locator('.rq-org .el-select__wrapper').click()
  await page.getByRole('option', { name: '8吋半导体', exact: true }).click()
  await page.locator('.rq-breadcrumb').click()
  await expect(query).toBeEnabled()
  await query.click()
  await expect(page.getByText('已查询', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/pms-query-stock.png' })
  await page.getByRole('button', { name: '采购进度', exact: true }).click()
  await expect(page.getByText('尚未查询', { exact: true })).toBeVisible()
  expect((await page.locator('.rq-grid-wrap').boundingBox()).y).toBeLessThan(190)
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.waitForTimeout(350)
  expect((await page.locator('.rq-grid-wrap').boundingBox()).y).toBeLessThan(230)
  await page.screenshot({ path: '/tmp/pms-query-compact-1366.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.waitForTimeout(3500)
  await expect(page.locator('.rq-stock')).not.toBeVisible()
  await page.getByRole('button', { name: '其他条件', exact: true }).click()
  await expect(page.locator('.rq-stock')).toBeVisible()
  await page.getByRole('button', { name: '收起', exact: true }).click()
  await page.screenshot({ path: '/tmp/pms-query-mobile.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
  expect(requests).toEqual([])
  console.log('PASS: explicit query, draft isolation, advanced conditions, saved plan, required fields, mobile, zero API calls')
} finally { await browser.close() }
