<script setup>
import { computed, nextTick, ref, watch } from 'vue'
import { Menu, Folder, Document, Setting, ArrowRight, ArrowDown, Close, Back } from '@element-plus/icons-vue'
import { PmsTextControl, PmsSelectControl, PmsDateControl } from '@/form-system'
import PmsReportQuerySurface from '@/report-query/PmsReportQuerySurface.vue'
import PmsReportQueryBar from '@/report-query/PmsReportQueryBar.vue'
import PmsReportPlans from '@/report-query/PmsReportPlans.vue'
import { validateConditions } from '@/report-query/state'
import DetailTable from './DetailTable.vue'
import { lines, states, summarize } from './data.js'

const designs = [
  { id: 'A', title: '双视图切换', note: '总表占满页面；点击项目明细后，进入该项目的完整明细。返回时保留总表位置。', advantage: '推荐：最省空间，现有明细体验基本不变。' },
  { id: 'B', title: '上下主从联动', note: '点击项目明细打开下方面板；面板打开后，点击上方其他项目即切换明细。', advantage: '适合连续比较项目；上下分屏会减少各自可见行数。' },
  { id: 'C', title: '项目行内展开', note: '在项目下方展开申请行，可同时展开多个项目；也可切换到全屏明细。', advantage: '上下文最直观；展开较多时，项目之间的距离会变长。' },
]
const initial = new URLSearchParams(location.search).get('variant')
const variant = ref(['A', 'B', 'C'].includes(initial) ? initial : 'A')
const design = computed(() => designs.find(d => d.id === variant.value))
const view = ref('summary'), embedded = ref(true), menuOpen = ref(false), showNotes = ref(false)
const keyword = ref(''), product = ref([]), dates = ref([]), conditions = ref([])
const applied = ref(null), queried = ref(false), dirty = computed(() => queried.value && JSON.stringify(snapshot()) !== JSON.stringify(applied.value))
const scope = ref(null), status = ref(''), summaryStatus = ref(''), linked = ref(null), expanded = ref([])
const page = ref(1), size = ref(50), scroll = ref(null), summaryScroll = ref(0), summaryPage = ref(1)
const selectedLine = ref(null), drawer = ref(false), columnsOpen = ref(false)
const allSummaryColumns = [
  ['code', '项目编号', 120], ['name', '项目名称', 150], ['product', '产品线', 88], ['organization', '请购组织', 150],
  ['total', '申请总行数', 80], ['percent', '行完成率', 130], ['not_ordered', '未下单', 68], ['ordering', '部分下单', 68], ['receiving', '待入库', 68], ['complete', '已完成', 68], ['review', '待核对', 68],
]
const visible = ref(allSummaryColumns.map(c => c[0])), draftVisible = ref([])
const summaryColumns = computed(() => allSummaryColumns.filter(c => visible.value.includes(c[0])))
const fields = [{ field: 'code', label: '项目编号', type: 'text' }, { field: 'material', label: '物料名称', type: 'text' }, { field: 'bill', label: '申请单编号', type: 'text' }, { field: 'requested', label: '申请数量', type: 'number' }]
const invalid = computed(() => validateConditions(conditions.value, fields))
function snapshot() { return { keyword: keyword.value, product: [...product.value], dates: [...dates.value], conditions: structuredClone(conditions.value.map(c => ({ ...c }))) } }
function restore(saved) { keyword.value = saved.keyword || ''; product.value = saved.product || []; dates.value = saved.dates || []; conditions.value = saved.conditions || []; queried.value = false; applied.value = null; clearContext() }
function clearContext() { scope.value = null; status.value = ''; summaryStatus.value = ''; linked.value = null; expanded.value = []; page.value = 1; drawer.value = false }
function query() { if (invalid.value) return; applied.value = snapshot(); queried.value = true; clearContext() }
function reset() { keyword.value = ''; product.value = []; dates.value = []; conditions.value = []; applied.value = null; queried.value = false; clearContext() }
function matches(row, c) {
  const value = row[c.field], a = c.value, b = c.valueEnd
  switch (c.operator) {
    case 'contains': return String(value).includes(String(a))
    case 'notContains': return !String(value).includes(String(a))
    case 'startsWith': return String(value).startsWith(String(a))
    case 'endsWith': return String(value).endsWith(String(a))
    case 'equals': return String(value) === String(a)
    case 'notEquals': return String(value) !== String(a)
    case 'greaterThan': return Number(value) > Number(a)
    case 'greaterOrEqual': return Number(value) >= Number(a)
    case 'lessThan': return Number(value) < Number(a)
    case 'lessOrEqual': return Number(value) <= Number(a)
    case 'between': return Number(value) >= Number(a) && Number(value) <= Number(b)
    case 'isEmpty': return value == null || value === ''
    case 'notEmpty': return value != null && value !== ''
    default: return false
  }
}
const result = computed(() => {
  const q = applied.value
  if (!queried.value || !q) return []
  return lines.filter(r => (!q.keyword || `${r.code} ${r.name} ${r.material} ${r.material_code} ${r.bill}`.includes(q.keyword))
    && (!q.product.length || q.product.includes(r.product))
    && (!q.dates.length || (r.date >= q.dates[0] && r.date <= q.dates[1])) && q.conditions.every(c => matches(r, c)))
})
const summaries = computed(() => summarize(result.value))
const summaryRows = computed(() => summaries.value.filter(r => !summaryStatus.value || (summaryStatus.value === 'complete' ? r.percent === 100 : summaryStatus.value === 'review' ? r.counts[4] > 0 : r.percent < 100)))
const detailRows = computed(() => result.value.filter(r => (!scope.value || r.project_id === scope.value.id) && (!status.value || r.progress === status.value)))
const total = computed(() => view.value === 'summary' ? summaryRows.value.length : detailRows.value.length)
const pagedSummary = computed(() => summaryRows.value.slice((page.value - 1) * size.value, page.value * size.value))
const pagedDetail = computed(() => detailRows.value.slice((page.value - 1) * size.value, page.value * size.value))
const totals = computed(() => ({ all: result.value.length, complete: result.value.filter(r => r.progress === 'complete').length, review: result.value.filter(r => r.progress === 'review').length }))
const pageCount = computed(() => Math.max(1, Math.ceil(total.value / size.value)))
function rememberSummary() { summaryScroll.value = scroll.value?.scrollTop || 0; summaryPage.value = page.value }
function allDetails() { if (view.value === 'summary') rememberSummary(); view.value = 'detail'; scope.value = null; status.value = ''; page.value = 1 }
async function back() { const wasDetail = view.value === 'detail'; view.value = 'summary'; scope.value = null; status.value = ''; if (wasDetail) page.value = summaryPage.value; drawer.value = false; await nextTick(); if (wasDetail && scroll.value) scroll.value.scrollTop = summaryScroll.value }
function openFull(row) { rememberSummary(); scope.value = row; view.value = 'detail'; page.value = 1 }
function drill(row, state = '') {
  rememberSummary()
  if (variant.value === 'B') { linked.value = row; status.value = state; return }
  if (variant.value === 'C' && !state) { expanded.value = expanded.value.includes(row.id) ? expanded.value.filter(id => id !== row.id) : [...expanded.value, row.id]; return }
  scope.value = row; status.value = state; view.value = 'detail'; page.value = 1
}
function selectProject(row) { if (variant.value === 'B' && linked.value) { linked.value = row; status.value = '' } }
const forProject = (row, state = '') => result.value.filter(r => r.project_id === row.id && (!state || r.progress === state))
function openLine(row) { selectedLine.value = row; drawer.value = true }
function selectLine(row) { if (drawer.value) selectedLine.value = row }
function changeVariant(value) { variant.value = value; view.value = 'summary'; clearContext(); history.replaceState(null, '', `?variant=${value}`) }
watch([size, summaryStatus], () => { page.value = 1 })
const batches = computed(() => {
  const r = selectedLine.value
  if (!r || !r.ordered) return []
  return [0, 1].map(i => ({ order: `CGDD2026${r.id.replace(/\D/g, '').padStart(4, '0')}${i + 1}`, date: i ? '2026-09-18' : '2026-09-10', qty: r.ordered / 2, received: r.received / 2, supplier: i ? '上海工艺设备有限公司' : '苏州精密配件有限公司' }))
})
// Preload fixtures for visual comparison only; reset demonstrates manual-query entry.
query()
</script>

<template>
  <div class="overview-prototype">
    <div class="review-strip"><strong>采购总进度 · 交互样稿</strong><div class="design-switch" role="group" aria-label="设计方案"><button v-for="d in designs" :key="d.id" :aria-pressed="variant === d.id" @click="changeVariant(d.id)">{{ d.id }} {{ d.title }}{{ d.id === 'A' ? '（推荐）' : '' }}</button></div><label><input v-model="embedded" type="checkbox"> 模拟OA占位</label><button class="text-action" @click="showNotes = !showNotes">{{ showNotes ? '收起说明' : '方案与口径' }}</button><span>模拟数据 · 不连接服务器</span></div>
    <div v-if="showNotes" class="design-notes"><strong>{{ design.title }}</strong><span>{{ design.note }} {{ design.advantage }}</span><p>演示口径：完成率 = 当前查询范围内的已完成申请行 / 全部申请行。待核对行不算完成；不是按数量或金额加权。相同项目号按请购组织分开。申请日期过滤后只统计该日期范围，不能称为项目全生命周期进度。撤销/关闭申请如何计入，待正式开发前确认。</p></div>
    <div :class="['oa-shell', { embedded }]">
      <aside v-if="embedded" class="oa-placeholder"><strong>OA</strong><span>公司系统</span><span>报表</span><span>研发项目</span><span class="current">PMS</span><small>仅模拟宿主占用宽度<br>不改OA菜单</small></aside>
      <div class="pms-shell" :class="{ 'menu-open': menuOpen }">
        <header class="workspace-head"><button class="icon-button" aria-label="展开或收起菜单" @click="menuOpen = !menuOpen"><el-icon><Menu /></el-icon></button><strong>采购进度查询</strong><span>样稿管理员</span></header>
        <nav class="side-menu"><div class="brand">P</div><div class="nav-item" tabindex="0"><el-icon><Folder /></el-icon><span v-if="menuOpen">项目管理</span><div class="flyout">项目档案<br>项目进度</div></div><div class="nav-item current" tabindex="0"><el-icon><Document /></el-icon><span v-if="menuOpen">采购进度查询</span><div class="flyout">采购进度查询<br>即时库存查询<br>物料收发明细</div></div><div class="nav-item" tabindex="0"><el-icon><Setting /></el-icon><span v-if="menuOpen">系统管理</span><div class="flyout">用户管理<br>角色管理</div></div></nav>
        <main class="workspace-main"><section class="report-panel">
          <PmsReportQuerySurface>
            <div class="pms-report-query-toolbar pms-query-density"><div class="view-switch" role="group" aria-label="报表视图"><button :aria-pressed="view === 'summary'" @click="back">项目总进度</button><button :aria-pressed="view === 'detail'" @click="allDetails">采购明细</button></div><PmsReportPlans storage-key="pms:prototype:purchase-overview:v1" :snapshot="snapshot" @restore="restore" /><div class="toolbar-end"><span>{{ dirty ? '条件已修改，待查询' : queried ? '已查询 · 模拟数据' : '尚未查询' }}</span><el-button v-if="view === 'summary'" @click="draftVisible = [...visible]; columnsOpen = true">列设置</el-button></div></div>
            <PmsReportQueryBar v-model:conditions="conditions" :fields="fields" :invalid="invalid" @query="query" @reset="reset"><div class="query-material keyword"><PmsTextControl v-model="keyword" size="compact" placeholder="项目 / 申请单 / 物料编码或名称" aria-label="关键词" clearable /></div><div class="query-material product"><PmsSelectControl v-model="product" size="compact" :options="[{value:'8吋Bench',label:'8吋Bench'},{value:'Single',label:'Single'}]" multiple collapse-tags clearable placeholder="全部产品线" aria-label="产品线" /></div><div class="query-dates dates"><PmsDateControl v-model="dates" size="compact" type="daterange" value-format="YYYY-MM-DD" start-placeholder="申请开始日期" end-placeholder="申请结束日期" aria-label="申请日期范围" /></div></PmsReportQueryBar>
          </PmsReportQuerySurface>
          <div class="quick-strip"><template v-if="view === 'summary'"><button v-for="s in [{value:'',label:'全部项目'},{value:'unfinished',label:'未完成'},{value:'complete',label:'已完成'},{value:'review',label:'含待核对'}]" :key="s.value" :aria-pressed="summaryStatus === s.value" @click="summaryStatus = s.value">{{ s.label }}</button><span class="summary-caption">{{ summaries.length }} 个项目组织组合 · {{ totals.all }} 申请行 · 已完成 {{ totals.complete }} 行<span v-if="totals.review"> · 待核对 {{ totals.review }} 行</span></span></template><template v-else><button :aria-pressed="status === ''" @click="status = ''; page = 1">全部</button><button v-for="s in states" :key="s.value" :aria-pressed="status === s.value" @click="status = s.value; page = 1">{{ s.label }}</button><span class="summary-caption">申请行明细 · {{ scope ? '当前项目' : '当前查询范围全部项目' }}</span></template></div>
          <div v-if="view === 'detail'" class="context-strip"><button class="text-action" @click="back"><el-icon><Back /></el-icon>返回总进度</button><template v-if="scope"><strong>{{ scope.code }}</strong><span>{{ scope.product }} · {{ scope.organization }}</span><button class="text-action" @click="scope = null; status = ''; page = 1">清除项目限定</button></template><span v-else>全部符合公共查询条件的申请行</span></div>
          <div class="table-layout" :class="{ split: variant === 'B' && linked && view === 'summary' }">
            <div ref="scroll" class="table-scroll">
              <table v-if="view === 'summary'" class="summary-table"><colgroup><col v-for="c in summaryColumns" :key="c[0]" :style="{ width: c[2] + 'px' }"><col style="width:96px"></colgroup><thead><tr><th v-for="c in summaryColumns" :key="c[0]">{{ c[1] }}</th><th class="action-cell">操作</th></tr></thead><tbody><template v-for="r in pagedSummary" :key="r.id"><tr :data-project="r.id" :class="{selected: linked?.id === r.id}" @click="selectProject(r)"><td v-for="c in summaryColumns" :key="c[0]" :title="['name','organization'].includes(c[0]) ? r[c[0]] : undefined"><template v-if="c[0] === 'percent'"><div class="completion"><span class="track"><span :class="{done:r.percent === 100}" :style="{width:r.percent+'%'}"></span></span><strong>{{ r.percent.toFixed(1) }}%</strong></div></template><button v-else-if="states.some(s => s.value === c[0])" :class="['count-link', { alert: c[0] === 'review' && r.counts[4] }]" @click.stop="drill(r, c[0])">{{ r.counts[states.findIndex(s => s.value === c[0])] }}</button><span v-else :class="{number:c[0] === 'total'}">{{ r[c[0]] }}</span></td><td class="action-cell"><button class="text-action" @click.stop="drill(r)"><el-icon v-if="variant === 'C'"><ArrowDown v-if="expanded.includes(r.id)" /><ArrowRight v-else /></el-icon>{{ variant === 'C' ? expanded.includes(r.id) ? '收起' : '展开' : '明细' }}</button></td></tr><tr v-if="variant === 'C' && expanded.includes(r.id)" class="expanded-row"><td :colspan="summaryColumns.length + 1"><div class="expanded-title"><strong>{{ r.code }} · {{ r.product }}</strong><span>{{ forProject(r).length }} 申请行</span><button class="text-action" @click="openFull(r)">全屏查看</button></div><div class="nested-scroll"><DetailTable :rows="forProject(r)" :active-id="selectedLine?.id" @open="openLine" @select="selectLine" /></div></td></tr></template></tbody></table>
              <DetailTable v-else :rows="pagedDetail" :active-id="selectedLine?.id" @open="openLine" @select="selectLine" />
              <div v-if="view === 'summary' && !pagedSummary.length" class="empty-state">{{ queried ? '没有符合条件的项目' : '设置条件后，点击查询' }}<small v-if="!queried">默认进入项目总进度，不自动读取业务数据</small></div>
            </div>
            <section v-if="variant === 'B' && linked && view === 'summary'" class="linked-panel"><header><strong>{{ linked.code }} · {{ linked.product }}</strong><span>{{ linked.organization }}</span><span>{{ forProject(linked, status).length }} 申请行{{ status ? ' · ' + states.find(s => s.value === status)?.label : '' }}</span><button class="text-action" @click="openFull(linked)">全屏明细</button><button class="icon-button" aria-label="关闭联动明细" @click="linked = null"><el-icon><Close /></el-icon></button></header><div class="linked-scroll"><DetailTable :rows="forProject(linked, status)" :active-id="selectedLine?.id" @open="openLine" @select="selectLine" /></div></section>
          </div>
          <footer class="report-footer"><span>共 {{ total }} {{ view === 'summary' ? '项' : '行' }}</span><div class="page-controls"><button aria-label="上一页" :disabled="page <= 1" @click="page--">‹</button><span>{{ page }} / {{ pageCount }}</span><button aria-label="下一页" :disabled="page >= pageCount" @click="page++">›</button></div><select v-model.number="size" aria-label="每页条数"><option :value="10">10 条/页</option><option :value="50">50 条/页</option><option :value="100">100 条/页</option></select></footer>
        </section><div class="design-caption"><strong>方案 {{ variant }}</strong><span>{{ design.note }}</span><button class="text-action" @click="query">载入演示数据</button></div></main>
      </div>
    </div>
    <el-dialog v-model="columnsOpen" title="总进度显示字段（样稿）" width="480px"><el-checkbox-group v-model="draftVisible"><el-checkbox v-for="c in allSummaryColumns" :key="c[0]" :label="c[1]" :value="c[0]" :disabled="c[0] === 'code'" /></el-checkbox-group><template #footer><el-button @click="columnsOpen = false">取消</el-button><el-button type="primary" @click="visible = [...draftVisible]; columnsOpen = false">保存</el-button></template></el-dialog>
    <el-drawer v-model="drawer" title="采购申请行明细 · 模拟批次" size="min(760px, 95vw)"><template v-if="selectedLine"><div class="line-context"><strong>{{ selectedLine.code }} · {{ selectedLine.product }}</strong><span>{{ selectedLine.bill }} / 第 {{ selectedLine.line }} 行</span><span>{{ selectedLine.material }} · {{ selectedLine.spec }}</span></div><h3>关联采购订单</h3><div class="drawer-scroll"><table><thead><tr><th>订单编号</th><th>订单日期</th><th>供应商</th><th>订单数量</th></tr></thead><tbody><tr v-for="b in batches" :key="b.order"><td>{{ b.order }}</td><td>{{ b.date }}</td><td>{{ b.supplier }}</td><td class="number">{{ b.qty }}</td></tr><tr v-if="!batches.length"><td colspan="4">尚未下单</td></tr></tbody></table></div><h3>关联采购入库</h3><div class="drawer-scroll"><table><thead><tr><th>关联订单</th><th>入库批次</th><th>入库日期</th><th>实收数量</th></tr></thead><tbody><template v-for="b in batches" :key="b.order"><template v-if="b.received"><tr v-for="i in [1,2]" :key="i"><td>{{ b.order }}</td><td>第 {{ i }} 批</td><td>{{ i === 1 ? '2026-09-20' : '2026-09-24' }}</td><td class="number">{{ b.received / 2 }}</td></tr></template></template><tr v-if="!selectedLine.received"><td colspan="4">尚无入库记录</td></tr></tbody></table></div></template></el-drawer>
  </div>
</template>

<style>
html,body,#app{height:100%;margin:0}body{font-family:var(--pms-font);color:var(--pms-text);font-size:13px}*{box-sizing:border-box}button,input,select{font:inherit}button{cursor:pointer}button:focus-visible,select:focus-visible,.nav-item:focus-visible{outline:2px solid var(--pms-primary);outline-offset:1px}button:disabled{cursor:default;color:var(--pms-text-muted)}
.overview-prototype{height:100%;display:flex;flex-direction:column;background:var(--pms-bg)}.review-strip{display:flex;align-items:center;flex-wrap:wrap;gap:12px;min-height:46px;padding:7px 12px;background:white;border-bottom:1px solid var(--pms-border);font-size:12px}.review-strip>span{margin-left:auto;color:var(--pms-text-muted)}.review-strip label{display:flex;align-items:center;gap:4px}.design-switch,.view-switch{display:flex;align-items:center;gap:2px;border:1px solid var(--pms-border);border-radius:4px;padding:2px}.design-switch button,.view-switch button{border:0;background:transparent;color:var(--pms-text-secondary);height:24px;padding:0 10px;border-radius:3px;white-space:nowrap;font-size:12px}.design-switch button[aria-pressed=true],.view-switch button[aria-pressed=true]{color:var(--pms-primary);background:var(--pms-primary-soft);font-weight:600}.design-notes{padding:10px 16px;border-bottom:1px solid var(--pms-border);background:white;font-size:12px;line-height:1.8}.design-notes>strong{margin-right:12px}.design-notes p{margin:5px 0 0;color:var(--pms-text-secondary)}
.oa-shell{display:grid;grid-template-columns:minmax(0,1fr);min-height:0;flex:1}.oa-shell.embedded{grid-template-columns:156px minmax(0,1fr)}.oa-placeholder{display:flex;flex-direction:column;gap:24px;padding:18px 14px;background:#f0f3f8;border-right:1px solid #d9e1ec;color:#65748b;font-size:12px}.oa-placeholder strong{font-size:16px;color:#3f597e}.oa-placeholder .current{background:#e1e7f2;padding:8px;border-radius:4px}.oa-placeholder small{margin-top:auto;line-height:1.7;color:#8895a9}.pms-shell{display:grid;grid-template-columns:64px minmax(0,1fr);grid-template-rows:44px minmax(0,1fr);min-width:0;min-height:0}.pms-shell.menu-open{grid-template-columns:184px minmax(0,1fr)}.workspace-head{grid-column:1/-1;display:flex;align-items:center;gap:10px;padding:0 10px;background:white;border-bottom:1px solid var(--pms-border-soft)}.workspace-head>strong{font-size:14px}.workspace-head>span{margin-left:auto;color:var(--pms-text-secondary);font-size:12px}.icon-button{display:inline-flex;align-items:center;justify-content:center;width:24px;height:24px;padding:0;border:0;background:transparent;color:var(--pms-text-secondary);flex-shrink:0}.side-menu{background:white;border-right:1px solid var(--pms-border-soft);padding:8px;z-index:4}.brand{height:28px;width:28px;margin:0 auto 18px;display:grid;place-items:center;border-radius:5px;background:var(--pms-primary-soft);color:var(--pms-primary);font-weight:700}.nav-item{display:flex;gap:10px;align-items:center;justify-content:center;height:36px;margin-bottom:5px;border-radius:4px;position:relative;color:var(--pms-text-secondary)}.nav-item.current{color:var(--pms-primary);background:var(--pms-primary-soft)}.menu-open .nav-item{justify-content:flex-start;padding-left:12px}.flyout{display:none;position:absolute;left:100%;top:0;width:155px;padding:8px 14px;border:1px solid var(--pms-border);background:white;box-shadow:0 4px 12px #1c294515;line-height:30px;color:var(--pms-text-secondary)}.nav-item:hover .flyout,.nav-item:focus .flyout{display:block}
.workspace-main{min-width:0;min-height:0;padding:6px;display:flex;flex-direction:column;gap:4px}.report-panel{flex:1;min-height:0;min-width:0;display:flex;flex-direction:column;padding:8px;background:white;border:1px solid var(--pms-border-soft);border-radius:6px}.pms-report-query-toolbar{flex-wrap:wrap}.toolbar-end{margin-left:auto;display:flex;align-items:center;gap:8px}.toolbar-end>span{font-size:11px;color:var(--pms-text-muted)}.view-switch{padding:1px}.view-switch button{height:22px}.overview-prototype .pms-report-query-surface .pms-report-query-fields>.keyword{width:245px}.overview-prototype .pms-report-query-surface .pms-report-query-fields>.product{width:150px}.overview-prototype .pms-report-query-surface .pms-report-query-fields>.dates{width:255px}.quick-strip{display:flex;align-items:center;gap:18px;min-height:28px;flex-wrap:wrap;border-bottom:1px solid var(--pms-border-soft);margin-bottom:4px}.quick-strip>button{border:0;border-bottom:2px solid transparent;background:transparent;font-size:12px;height:26px;padding:0;color:var(--pms-text-secondary)}.quick-strip>button[aria-pressed=true]{color:var(--pms-primary);border-bottom-color:var(--pms-primary)}.summary-caption{margin-left:auto;color:var(--pms-text-muted);font-size:11px}.context-strip{display:flex;align-items:center;gap:10px;min-height:28px;font-size:12px;padding-bottom:4px}.context-strip>span{color:var(--pms-text-secondary)}.text-action{display:inline-flex;align-items:center;gap:3px;border:0;background:transparent;color:var(--pms-primary);font-size:12px;padding:0 4px;min-height:24px;white-space:nowrap}.text-action:hover{text-decoration:underline}
.table-layout{flex:1;min-height:0;display:flex;flex-direction:column;border:1px solid var(--pms-border-soft);border-radius:4px;overflow:hidden}.table-scroll{flex:1;min-height:0;overflow:auto;position:relative}.overview-prototype table{border-collapse:separate;border-spacing:0;table-layout:fixed;width:100%;font-size:13px}.summary-table{min-width:1154px}.detail-table{min-width:1560px}.overview-prototype th{position:sticky;top:0;z-index:2;height:30px;background:var(--pms-surface-soft,#f7f9fc);text-align:center;font-size:12px;font-weight:600;color:var(--pms-text-secondary);border-bottom:1px solid var(--pms-border);border-right:1px solid var(--pms-border-soft);padding:0 8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.overview-prototype td{height:32px;padding:0 10px;border-bottom:1px solid var(--pms-border-soft);border-right:1px solid var(--pms-border-soft);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;background:white}.overview-prototype tbody>tr:nth-child(even)>td{background:#fafbfd}.overview-prototype tbody>tr:hover>td{background:#f5f7fd}.overview-prototype tbody>tr.selected>td{background:#eef0ff}.overview-prototype .number{display:block;text-align:right;font-variant-numeric:tabular-nums}.overview-prototype td.number{display:table-cell}.count-link{border:0;background:transparent;color:var(--pms-text-secondary);padding:0;width:100%;height:28px;text-align:right;font-variant-numeric:tabular-nums}.count-link:hover{color:var(--pms-primary);text-decoration:underline}.count-link.alert{color:var(--pms-danger,#dc3854)}.completion{display:flex;align-items:center;gap:8px}.completion strong{min-width:44px;text-align:right;font-size:12px;font-weight:500;font-variant-numeric:tabular-nums}.track{flex:1;height:5px;background:#e9edf5;border-radius:3px;overflow:hidden}.track>span{display:block;height:100%;background:#8b87db;border-radius:3px}.track>span.done{background:#38a898}.overview-prototype .action-cell{position:sticky;right:0;z-index:1;text-align:center;background:#f3f5fa;box-shadow:-1px 0 0 var(--pms-border)}.overview-prototype th.action-cell{z-index:3;background:#eef1f7}.detail-table th:nth-child(1){width:125px}.detail-table th:nth-child(2){width:100px}.detail-table th:nth-child(3){width:145px}.detail-table th:nth-child(4){width:150px}.detail-table th:nth-child(5){width:132px}.detail-table th:nth-child(6){width:60px}.detail-table th:nth-child(7){width:112px}.detail-table th:nth-child(8){width:85px}.detail-table th:nth-child(9){width:100px}.detail-table th:nth-child(10),.detail-table th:nth-child(11){width:120px}.detail-table th:nth-child(12){width:122px}.detail-table th:nth-child(13){width:80px}.empty-state{padding:80px 20px;text-align:center;color:var(--pms-text-secondary)}.empty-state small{display:block;margin-top:10px;color:var(--pms-text-muted)}.empty-cell{text-align:center;color:var(--pms-text-muted)}
.split>.table-scroll{flex:1 1 50%}.linked-panel{flex:1 1 46%;min-height:180px;display:flex;flex-direction:column;border-top:2px solid #cfd7e7}.linked-panel>header,.expanded-title{display:flex;align-items:center;gap:10px;background:#f6f8fc;min-height:30px;padding:0 10px;font-size:12px}.linked-panel>header>span{color:var(--pms-text-secondary)}.linked-panel>header>.text-action,.expanded-title>.text-action{margin-left:auto}.linked-scroll{flex:1;min-height:0;overflow:auto}.overview-prototype tr.expanded-row>td{padding:0 0 8px 18px;background:#f2f5fa}.nested-scroll{max-height:238px;overflow:auto;border-left:2px solid #cfd7e7}.expanded-title>span{color:var(--pms-text-muted)}.report-footer{display:flex;align-items:center;justify-content:space-between;gap:8px;padding-top:4px;min-height:32px;font-size:12px;color:var(--pms-text-secondary)}.page-controls{display:flex;align-items:center;gap:8px}.page-controls button,.report-footer select{height:26px;min-width:26px;border:1px solid var(--pms-border);border-radius:4px;background:white;color:var(--pms-text-secondary)}.page-controls button{font-size:17px}.report-footer select{font-size:12px;padding:0 6px}.design-caption{display:flex;gap:8px;align-items:center;min-height:25px;padding:0 3px;font-size:11px;color:var(--pms-text-muted)}.design-caption>strong{color:var(--pms-text-secondary)}.design-caption>.text-action{margin-left:auto;font-size:11px}.line-context{display:flex;flex-direction:column;gap:8px;font-size:13px}.line-context>span{color:var(--pms-text-secondary)}.overview-prototype h3{font-size:13px;margin:24px 0 8px}.drawer-scroll{overflow:auto}.drawer-scroll table{min-width:650px}.el-checkbox-group{display:grid;grid-template-columns:1fr 1fr}
@media(max-width:1000px){.review-strip>span{display:none}.oa-shell.embedded{grid-template-columns:110px minmax(0,1fr)}.summary-caption{display:none}.pms-report-query-fields>.keyword{width:210px}.pms-report-query-fields>.dates{width:230px}.design-caption>span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.toolbar-end>span{display:none}}
@media(max-width:600px){.oa-shell.embedded{grid-template-columns:minmax(0,1fr)}.oa-placeholder{display:none}.review-strip{gap:5px}.review-strip>strong{width:100%}.design-switch{width:100%}.design-switch button{flex:1;padding:0 3px;font-size:11px}.pms-shell.menu-open{grid-template-columns:128px minmax(0,1fr)}.workspace-head>span{display:none}.pms-report-query-toolbar{gap:4px}.toolbar-end{margin-left:0}.pms-report-query-fields>.keyword,.pms-report-query-fields>.product,.pms-report-query-fields>.dates{width:100%}.quick-strip{gap:12px}.context-strip{flex-wrap:wrap}.linked-panel>header{flex-wrap:wrap;padding:5px}.design-caption>span{display:none}}
</style>
